/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesBioseguridadFinal;

import bioseguridadfinal.Encuesta;
import bioseguridadfinal.Fecha;
import bioseguridadfinal.Persona;
import java.awt.Dimension;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Paty
 */
public class Empezar extends javax.swing.JFrame {

    /**
     * Creates new form Empezar
     */
    public Empezar() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIOSEGURIDAD");

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Empezar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Andrés García, Oscar Rosero, Patty Zurita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuPrincipal mP = new  MenuPrincipal();
        mP.setVisible(true);
        this.setVisible(false);
        
        Fecha fechaNacimiento1=new Fecha(19,12,2000);
        Persona per1 = new Persona("1750823732", "Patty", "femenino",fechaNacimiento1,new ArrayList<Encuesta>());
        MenuPrincipal.persona.add(per1); 
        
        Fecha fechaNacimiento2=new Fecha(4,7,1999);
        Persona per2 = new Persona("1720114055", "Oscar", "masculino",fechaNacimiento2,new ArrayList<Encuesta>());
        MenuPrincipal.persona.add(per2); 
        
        Fecha fechaNacimiento3=new Fecha(14,2,1999);
        Persona per3 = new Persona("1722237862", "Andres", "masculino",fechaNacimiento3,new ArrayList<Encuesta>());
        MenuPrincipal.persona.add(per3); 
        
        boolean fi = true;
        boolean fa = true;
        boolean to = true;
        boolean es = true;
        boolean dm = true;
        boolean cg = true;
        boolean dg = true;
        boolean di = true;
        boolean dc= true;
        boolean dr = true;
        boolean sa = true;
        boolean ct = true;
                        
        for (Persona persona : MenuPrincipal.persona) {
                    if(persona.getCedula().equals("1750823732")){
                        fi = true;
                        fa = true;
                        to = false;
                        es = true;
                        dm = true;
                        cg = true;
                        dg = false;
                        di = false;
                        dc= true;
                        dr = true;
                        sa = false;
                        ct = false;
                        
                        Fecha fechaEncuesta=new Fecha(15,06,2019);
                        Encuesta encuesta = new Encuesta(sa,ct,fi, fa,to,es, dm, cg, dg, di, dc,dr, fechaEncuesta);
                        persona.anadirEncuesta(encuesta);
                        break;
                }
        }
        for (Persona persona : MenuPrincipal.persona) {
                    if(persona.getCedula().equals("1750823732")){
                        fi = false;
                        fa = true;
                        to = false;
                        es = true;
                        dm = true;
                        cg = true;
                        dg = true;
                        di = false;
                        dc= false;
                        dr = true;
                        sa = true;
                        ct = false;
                        
                        Fecha fechaEncuesta=new Fecha(7,1,2019);
                        Encuesta encuesta = new Encuesta(sa,ct,fi, fa,to,es, dm, cg, dg, di, dc,dr, fechaEncuesta);
                        persona.anadirEncuesta(encuesta);
                        break;
                }
        }
        
        for (Persona persona : MenuPrincipal.persona) {
                    if(persona.getCedula().equals("1720114055")){
                        fi = false;
                        fa = false;
                        to = false;
                        es = true;
                        dm = true;
                        cg = false;
                        dg = true;
                        di = false;
                        dc= false;
                        dr = true;
                        sa = false;
                        ct = false;
                        
                        Fecha fechaEncuesta=new Fecha(17,11,2020);
                        Encuesta encuesta = new Encuesta(sa,ct,fi, fa,to,es, dm, cg, dg, di, dc,dr, fechaEncuesta);
                        persona.anadirEncuesta(encuesta);
                        break;
                }
        }
        
        for (Persona persona : MenuPrincipal.persona) {
                    if(persona.getCedula().equals("1722237862")){
                        fi = true;
                        fa = true;
                        to = false;
                        es = true;
                        dm = true;
                        cg = false;
                        dg = true;
                        di = false;
                        dc= true;
                        dr = true;
                        sa = false;
                        ct = true;
                        
                        Fecha fechaEncuesta=new Fecha(4,3,2020);
                        Encuesta encuesta = new Encuesta(sa,ct,fi, fa,to,es, dm, cg, dg, di, dc,dr, fechaEncuesta);
                        persona.anadirEncuesta(encuesta);
                        break;
                }
        }
        
        
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empezar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empezar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
