/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesBioseguridadFinal;

import bioseguridadfinal.Encuesta;
import bioseguridadfinal.Fecha;
import bioseguridadfinal.Persona;
import static interfacesBioseguridadFinal.MenuPrincipal.persona;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 *
 * @author Paty
 */
public class MenuPrincipal extends javax.swing.JFrame {
    static List<Persona> persona = new ArrayList<Persona>();
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setSize(new Dimension(480, 550));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarPersona = new javax.swing.JButton();
        realizarEncuesta = new javax.swing.JButton();
        buscarEncuestasPrevias = new javax.swing.JButton();
        buscarPersona = new javax.swing.JButton();
        mostrarEncuestas = new javax.swing.JButton();
        mostrarPersonas = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 500));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 509));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIOSEGURIDAD");

        agregarPersona.setBackground(new java.awt.Color(204, 255, 255));
        agregarPersona.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agregarPersona.setText("Agregar persona");
        agregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPersonaActionPerformed(evt);
            }
        });

        realizarEncuesta.setBackground(new java.awt.Color(204, 255, 255));
        realizarEncuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        realizarEncuesta.setText("Realizar Encuesta");
        realizarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarEncuestaActionPerformed(evt);
            }
        });

        buscarEncuestasPrevias.setBackground(new java.awt.Color(204, 255, 255));
        buscarEncuestasPrevias.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscarEncuestasPrevias.setText("Buscar encuestas previas");
        buscarEncuestasPrevias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEncuestasPreviasActionPerformed(evt);
            }
        });

        buscarPersona.setBackground(new java.awt.Color(204, 255, 255));
        buscarPersona.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buscarPersona.setText("Buscar persona");
        buscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPersonaActionPerformed(evt);
            }
        });

        mostrarEncuestas.setBackground(new java.awt.Color(204, 255, 255));
        mostrarEncuestas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mostrarEncuestas.setText("Mostrar encuestas");
        mostrarEncuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEncuestasActionPerformed(evt);
            }
        });

        mostrarPersonas.setBackground(new java.awt.Color(204, 255, 255));
        mostrarPersonas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mostrarPersonas.setText("Mostrar personas");
        mostrarPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPersonasActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(204, 255, 255));
        salir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarEncuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarEncuestasPrevias)
                    .addComponent(realizarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(agregarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(realizarEncuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(buscarEncuestasPrevias, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarEncuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(mostrarPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPersonaActionPerformed
        AgregarPersona aP = new AgregarPersona();
        aP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarPersonaActionPerformed

    private void realizarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarEncuestaActionPerformed
        RealizarEncuesta rE = new RealizarEncuesta();
        rE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_realizarEncuestaActionPerformed

    private void buscarEncuestasPreviasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEncuestasPreviasActionPerformed
        BuscarEncuestasPrevias bEP = new BuscarEncuestasPrevias();
        bEP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buscarEncuestasPreviasActionPerformed

    private void buscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPersonaActionPerformed
        BuscarPersona bP = new  BuscarPersona();
        bP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buscarPersonaActionPerformed

    private void mostrarEncuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEncuestasActionPerformed
        MostrarEncuestas mE = new  MostrarEncuestas();
        mE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mostrarEncuestasActionPerformed

    private void mostrarPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPersonasActionPerformed
        MostrarPersonas mP = new  MostrarPersonas();
        mP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mostrarPersonasActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPersona;
    private javax.swing.JButton buscarEncuestasPrevias;
    private javax.swing.JButton buscarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mostrarEncuestas;
    private javax.swing.JButton mostrarPersonas;
    private javax.swing.JButton realizarEncuesta;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
