/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesBioseguridadFinal;

import bioseguridadfinal.Encuesta;
import bioseguridadfinal.Fecha;
import bioseguridadfinal.Persona;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
//import java.awt.event.KeyAdapter;
//import java.awt.event.KeyEvent;
//import javax.swing.JTextField;

/**
 *
 * @author Osquitar
 */
public class RealizarEncuesta extends javax.swing.JFrame {
boolean fi=false;
boolean fa=false;
boolean to=false;
boolean es=false;
boolean dm=false;
boolean cg=false;
boolean dg=false;
boolean di=false;
boolean dc=false;
boolean dr=false;
boolean sa=false;
boolean ct=false;


    /**
     * Creates new form estesi
     */
    public RealizarEncuesta() {
        initComponents();
        this.setSize(new Dimension(480, 650));
          
        fiebre.setLayout(null);  
        fiebre.setVisible(true);
        
        
        fatiga.setLayout(null);  
        fatiga.setVisible(true);
        
        tos.setLayout(null);  
        tos.setVisible(true);
        
        estornudos.setLayout(null);  
        estornudos.setVisible(true);
        
        dolormuscular.setLayout(null);  
        dolormuscular.setVisible(true);
        
        congestion.setLayout(null);  
        congestion.setVisible(true);
        
        dolordegarganta.setLayout(null);  
        dolordegarganta.setVisible(true);
        
        diarrea.setLayout(null);  
        diarrea.setVisible(true);
        
        dolordecabeza.setLayout(null);  
        dolordecabeza.setVisible(true);
        
        dificultadpararespirar.setLayout(null);  
        dificultadpararespirar.setVisible(true);
        
        salir.setLayout(null);  
        salir.setVisible(true);
        
        contacto.setLayout(null);  
        contacto.setVisible(true);
        
        aceptar.setVisible(false);
        resultados.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fiebre = new javax.swing.JCheckBox();
        fatiga = new javax.swing.JCheckBox();
        tos = new javax.swing.JCheckBox();
        estornudos = new javax.swing.JCheckBox();
        dolormuscular = new javax.swing.JCheckBox();
        congestion = new javax.swing.JCheckBox();
        dolordegarganta = new javax.swing.JCheckBox();
        diarrea = new javax.swing.JCheckBox();
        dolordecabeza = new javax.swing.JCheckBox();
        dificultadpararespirar = new javax.swing.JCheckBox();
        salir = new javax.swing.JCheckBox();
        contacto = new javax.swing.JCheckBox();
        cedula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        errorcedula = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Encuesta");

        jLabel14.setText("Cédula");

        fiebre.setText("Fiebre");
        fiebre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiebreActionPerformed(evt);
            }
        });

        fatiga.setText("Fatiga");
        fatiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fatigaActionPerformed(evt);
            }
        });

        tos.setText("Tos");

        estornudos.setText("Estornudos");

        dolormuscular.setText("Dolor muscular");

        congestion.setText("Congestión");

        dolordegarganta.setText("Dolor de garganta");
        dolordegarganta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dolordegargantaActionPerformed(evt);
            }
        });

        diarrea.setText("Diarrea");

        dolordecabeza.setText("Dolor de cabeza");

        dificultadpararespirar.setText("Dificultad para respirar");

        salir.setText("¿Ha salido en las ultimas 48 horas?");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        contacto.setText("¿Se ha relacionado con personas que han llegado del extranjero?");

        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });
        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Subir encuesta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Seleccionar los sintomas o situaciones existentes");

        aceptar.setBackground(new java.awt.Color(0, 153, 153));
        aceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        aceptar.setForeground(new java.awt.Color(255, 255, 255));
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        resultados.setEditable(false);
        resultados.setColumns(20);
        resultados.setRows(5);
        jScrollPane1.setViewportView(resultados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fatiga, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fiebre, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tos, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estornudos, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dolormuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(congestion, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dolordegarganta, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diarrea, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dolordecabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dificultadpararespirar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contacto)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(50, 50, 50)
                                        .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(errorcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(397, 397, 397)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(aceptar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fiebre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fatiga, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estornudos, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dolormuscular, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(congestion, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dolordegarganta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(diarrea, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dolordecabeza, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dificultadpararespirar, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fiebreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiebreActionPerformed
         
    }//GEN-LAST:event_fiebreActionPerformed

    private void dolordegargantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dolordegargantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dolordegargantaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
       
    }//GEN-LAST:event_cedulaActionPerformed

    private void fatigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fatigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fatigaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean enc=false;
        
            if(cedula.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Se debe ingresar un número de cédula");
                enc=true;
            }else if(cedula.getText().length()<10){
                JOptionPane.showMessageDialog(null, "La cédula ingresada no cumple con los requisitos");
                enc=true;
            }else{
                for (Persona persona : MenuPrincipal.persona) {
                    if(persona.getCedula().equals(cedula.getText())){
                        enc=true;
                        if(fiebre.isSelected()){  
                            fi = true;
                            
                        }  
                        else{
                            fi = false;
                        }
                        if(fatiga.isSelected()){  
                            fa = true;
                        }  
                        else{
                            fa = false;
                        }
                        if(tos.isSelected()){  
                            to = true;
                        }  
                        else{
                            to = false;
                        }
                        if(estornudos.isSelected()){  
                            es = true;
                        }  
                        else{
                            es = false;
                        }
                        if(dolormuscular.isSelected()){  
                            dm = true;
                        }  
                        else{
                            dm = false;
                        }
                        if(congestion.isSelected()){  
                            cg = true;
                        }  
                        else{
                            cg = false;
                        }
                        if(dolordegarganta.isSelected()){  
                            dg = true;
                        }  
                        else{
                            dg = false;
                        }
                        if(diarrea.isSelected()){  
                            di = true;
                        }  
                        else{
                            di = false;
                        }
                        if(dolordecabeza.isSelected()){  
                            dc = true;
                        }  
                        else{
                            dc = false;
                        }
                        if(dificultadpararespirar.isSelected()){  
                            dr = true;
                        }  
                        else{
                            dr = false;
                        }
                        if(salir.isSelected()){  
                            sa = true;
                        }  
                        else{
                            sa = false;
                        }
                        if(contacto.isSelected()){  
                            ct = true;
                        }  
                        else{
                            ct = false;
                        }

                        Fecha fechaEncuesta=new Fecha(LocalDate.now().getDayOfMonth(),
                        LocalDate.now().getMonthValue(),LocalDate.now().getYear());
                        Encuesta encuesta = new Encuesta(sa,ct,fi, fa,to,es, dm, cg, dg, di, dc,dr, fechaEncuesta);
                        persona.anadirEncuesta(encuesta);
                        
                        //JOptionPane.showMessageDialog(null, "**********RESULTADOS**********"+persona.mostrarInformacionEncuesta(fechaEncuesta)+"\n"+
                        //    persona.verResultadoEncuesta(fechaEncuesta));
                        aceptar.setVisible(true);
                        resultados.setVisible(true);
                        resultados.setText("**********RESULTADOS**********"+persona.verResultadoEncuesta(fechaEncuesta));
                        jButton1.setVisible(false);
                        
                        
                        
                        break;
                }else{
                    enc = false;
                }
                    
                }
            }
                if (enc==false){
                    JOptionPane.showMessageDialog(null, "No se encontró persona con la cédula ingresada");
                }
               
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
            if(cedula.getText().length()>=10){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            }
            if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
            errorcedula.setText("Escribe solo números");
            } else{
            errorcedula.setText("");
            }
            
    }//GEN-LAST:event_cedulaKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuPrincipal mP = new  MenuPrincipal();
        mP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        RealizarEncuesta.this.dispose();
        MenuPrincipal mP = new  MenuPrincipal();
        mP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField cedula;
    private javax.swing.JCheckBox congestion;
    private javax.swing.JCheckBox contacto;
    private javax.swing.JCheckBox diarrea;
    private javax.swing.JCheckBox dificultadpararespirar;
    private javax.swing.JCheckBox dolordecabeza;
    private javax.swing.JCheckBox dolordegarganta;
    private javax.swing.JCheckBox dolormuscular;
    private javax.swing.JLabel errorcedula;
    private javax.swing.JCheckBox estornudos;
    private javax.swing.JCheckBox fatiga;
    private javax.swing.JCheckBox fiebre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultados;
    private javax.swing.JCheckBox salir;
    private javax.swing.JCheckBox tos;
    // End of variables declaration//GEN-END:variables
}
